services:
  db:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'ny_taxi'
    ports:
      - '5433:5432'
    volumes:
      - vol-pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False" # Needed for rendering issues. 
      PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: "False" # Needed for rendering issues.
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: "False" # Needed for rendering issues.
      PGADMIN_CONFIG_SESSION_COOKIE_SAMESITE: "'None'" # Needed for rendering issues.
      PGADMIN_CONFIG_SESSION_COOKIE_SECURE: "True" # Needed for rendering issues.
    ports:
      - "8080:80"
    volumes:
      - vol-pgadmin_data:/var/lib/pgadmin

volumes:
  vol-pgdata:
    name: vol-pgdata
  vol-pgadmin_data:
    name: vol-pgadmin_data